### PR TITLE
Update bb-storage and dependencies

### PR DESCRIPTION
**Pull request by jlaxson**
Many of the shared config items in bb-storage have changed (like config.global), making it difficult to share that between 'latest' bb-remote-asset and bb-storage.  This is a combination of `go get`, `bazel run //:gazelle -- update-repos -from_file=go.mod`, and updating the targets in the bazel remote-execution repo that bb-storage is renaming.  But honestly I have no idea what I'm doing.

### CODE REVIEW

**Comment by jlaxson** [comment]
Needs buildbarn/storage#119 and another go get first.

**Comment by jlaxson** [comment]
@Qinusty Could you take a look here too

**Comment by Qinusty** [comment]
Looks like the remote-apis project is still using the go_default_library naming @jlaxson https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/BUILD#L57-L61

**Comment by jlaxson** [comment]
Yes, but it's patched by bb-storage (we were already doing this for the execution package) https://github.com/buildbarn/bb-storage/blob/master/patches/com_github_bazelbuild_remote_apis/golang.diff.  I don't really understand when/why gazelle chooses go_default_library vs execution - I fixed that patch because it insisted that the correct name was execution

**Comment by Qinusty** [comment]
hmmmm, are you able to reproduce these gazelle diffs locally? I'm not exactly sure what is causing this because the patch seems to be correct using the version of bb_storage in `go_dependencies.bzl`

**Comment by jjardon** [comment]
@tomcoldrick-ct I pretty sure this is obsolete now, can you confirm, please?

**Comment by tomcoldrick-ct** [comment]
This is now obsolete.

**Pull request closed without merging**
